# Generated by Django 4.1.5 on 2023-01-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('place', models.CharField(choices=[('qashqadaryo', 'Qashqadaryo'), ('andijon', 'Andijon'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('namangan', 'Namangan'), ('guliston', 'Guliston'), ("farg'ona", "Farg'ona"), ('toshkent', 'Toshkent'), ('surxondaryo', 'Surxondaryo'), ('xorazm', 'Xorazm'), ('navoiy', 'Navoiy'), ('sirdaryo', 'Sirdaryo'), ('jizzax', 'Jizzax')], max_length=120)),
                ('phone_number', models.CharField(max_length=13)),
                ('message', models.TextField()),
            ],
        ),
    ]
